### ISSUE TITLE
CRUDを作ってみました。テストです。

### ISSUE THREAD

**Issue by hideyasu2015** [tozan-miyage/Object#1]
これであっているかの確認をお願いします。
https://github.com/tozan-miyage/Object/blob/baa132726c9daf7012ac6789a6988bbfeaf6a340/routes/web.php#L19

**Comment by tozan-miyage** [comment]
はい、合っていると思います。始めは、このルーティングで試していたのですが、現在の
Route::get('/groups','GroupsController@index')->name('groups.index');
に変更していました。

**Comment by tozan-miyage** [comment]
issuesの記入は、こんな感じでよろしいのでしょうか？？

**Comment by hideyasu2015** [comment]
はい、良いですね。
テスト完了したので CLOSEしておきますね。
